### PR TITLE
accessibility documentation

### PR DESCRIPTION
**Pull request by jschuler**
Just straight up copied from pf4.patternfly.org

Needs any edits or styling updates? @rachael-phillips @stacymcauliffe 

Preview:
http://pf-a11y.surge.sh/get-started/accessibility

### CODE REVIEW

**Comment by stacymcauliffe** [comment]
My main comment about this doc would be the readability of the tables. The tag formatting is gone and it's a bit hard to follow content across each line item. I'd leave it to @jgiardino  to comment on the completeness of the content, but always happy to review for style.

**Comment by jgiardino** [comment]
Thanks for commenting on that, @stacymcauliffe. I agree the styles on the table need some help. I'm open to suggestion on that, but also happy to make suggestions. 

The list styles are a little odd too (e.g. sub-bullets are closer to the next parent bullet than to their parent bullet).

But the contents all seem to be there.

**Comment by rachael-phillips** [comment]
@christiemolloy is this something we can get up with styling on for May 3? You and I can pair to give this page some help early next week if you are open.

**Comment by jschuler** [comment]
Looks like A11y guide was merged in a different PR

**Pull request closed without merging**
