### PR TITLE
Add usage guidelines for sort component

### PR DESCRIPTION
**Pull request by gdoyle1**
Added usage guidelines for sort based on @KendraMar 's suggestions

### CODE REVIEW

**Comment by KendraMar** [comment]
Cheers, @gdoyle1 !

**Comment by gdoyle1** [comment]
@mcarrano Maybe I can separate the "Example" part out into another header and paragraph?

**Comment by mcarrano** [comment]
Sure, you can try that @gdoyle1 . The key is to leave a space between paragraphs in the Markdown if you want GitHub to see the new paragraph.

**Comment by gdoyle1** [comment]
@mcarrano Added some updates to the formatting

**Pull request merged**
