### PR TITLE
Update Contribution Guidelines

### PR DESCRIPTION
**Pull request by mindreeper2420**
Update the Contribution Guidelines page per Google doc and include the update in the What's New section.

### CODE REVIEW

**Comment by mindreeper2420** [comment]
I've created a PR to the Contributor Covenant repo to add PatternFly to their list of adopters.

**Comment by dlabrecq** [comment]
LGTM

**Comment by LHinson** [comment]
LGTM!

**Comment by LHinson** [comment]
Can we go ahead and merge this @dlabrecq?

**Pull request merged**
