### PR TITLE
PTNFLY-1587 Add About Modal live example to page.

### PR DESCRIPTION
**Pull request by cardosogabriel**

### CODE REVIEW

**Comment by dlabrecq** [comment]
LGTM

**Comment by LHinson** [comment]
@priley86 do you mind checking this one as well?

**Comment by LHinson** [comment]
@priley86 @jeff-phillips-18 @dgutride can one of you double check this? Hoping to get this merged before the release tomorrow.

**Comment by LHinson** [comment]
@andresgalante can you check please

**Comment by priley86** [comment]
@LHinson i pulled this down and tested the changes locally, the modal came up just fine. 

@cardosogabriel do you mind rebasing?

**Comment by cardosogabriel** [comment]
@priley86 It is rebased, thanks all for the review.

**Comment by priley86** [comment]
LGTM 👍  @cardosogabriel

**Pull request merged**
