### PR TITLE
added CSS variables documentation to the vars grid

### PR DESCRIPTION
**Pull request by stacymcauliffe**
I added CSS variables documentation to the CSS variables grid. I'm not sure how to preview this content. Adding Adam and Christie to review while Joachim is out.

### CODE REVIEW

**Comment by mindreeper2420** [comment]
@stacymcauliffe this is how the content additions look on the site:

Screen Shot 2019-04-25 at 11 44 19 AM

**Comment by stacymcauliffe** [comment]
@mindreeper2420 - add the className. Let me know if it makes a difference or if there is additional info I need to add to create line breaks between paragraphs. Thanks!

**Comment by mindreeper2420** [comment]
@stacymcauliffe here is an updated screenshot - looks a lot better now! If this is okay with you, I can approve and merge into master.

Screen Shot 2019-04-25 at 2 09 14 PM

**Comment by stacymcauliffe** [comment]
Awesome, thank you!

**Pull request merged**
