### PR TITLE
added UploadIcon to icons table

### LINKED ISSUE #2322: Add FA upload icon to icons table
Request to add the font awesome `upload` [icon](https://fontawesome.com/icons/upload?style=solid) to the icons table. We are already using this icon in the [code editor component](https://www.patternfly.org/v4/components/code-editor) examples.

Style: fas
Name: fa-upload
React_name: UploadIcon
Type: Action
Contextual_usage: Indicates an upload function is available

Screen Shot 2020-12-14 at 2 33 51 PM

cc: @bdellasc @mceledonia @evwilkin

### PR DESCRIPTION
**Pull request by evwilkin**
Closes #2322 

This PR adds the fa-upload/UploadIcon to the icons table.

### CODE REVIEW

**Comment by evwilkin** [comment]
@gdoyle1 thanks for providing all the details in the original issue, it was almost as easy as copy-pasting to add this new icon

Screen Shot 2020-12-16 at 3 40 42 PM

**Comment by bdellasc** [comment]
Looks good to me. Thanks!

**Review by bdellasc — APPROVED** [review]
Looks good to me, thanks!

**Review by gdoyle1 — APPROVED** [review]
LGTM!!!

**Pull request merged**
