### PR TITLE
adds the pf conference website

### PR DESCRIPTION
**Pull request by andresgalante**
@LHinson @bleathem It adds the conference website

### CODE REVIEW

**Comment by LHinson** [comment]
bitmoji

**Comment by bleathem** [comment]
-1 for browsersync, we already have a livereload mechanism setup for working with the site.  I can work with you to adapt it to this folder.

Also can we use less, or static CSS? adding another CSS processor will slow down the build for every execution moving forward.

**Comment by andresgalante** [comment]
I am committing the css folder, so we don't have to build anything. Can this be a standalone thing? link it someway from somewhere else?

**Comment by bleathem** [comment]
This PR has been superceded by this one:
https://github.com/patternfly/patternfly-org/pull/394

**Pull request closed without merging**
