### PR TITLE
add release notes, bump repos, add script to checkout version

### PR DESCRIPTION
**Pull request by redallen**
Add release notes pages for both Core and React on their respective sidebars.

To preview the design, you can look at https://pf4-release-notes.surge.sh

### CODE REVIEW

**Comment by dgutride** [comment]
@redallen  - can we kick this build and get a preview of this?

**Comment by redallen** [comment]
@dgutride Done. https://pf4-release-notes.surge.sh

**Comment by rachael-phillips** [comment]
@redallen here are the notes from our meeting: 

- Background grey needs to match the background of other page
- Pr links on second half of the page
- Link to npms
- Auto-link headers

**Comment by redallen** [comment]
@rachael-phillips I edited the markdown upstream to fix the links and headers, and I changed the background color. Please re-review the preview: https://pf4-release-notes.surge.sh/documentation/react/notes/ and https://pf4-release-notes.surge.sh/documentation/core/notes/!

**Comment by redallen** [comment]
Updated to have latest 2019.05 release notes (2019-07-24).

**Comment by redallen** [comment]
@rachael-phillips Please take (yet another) look at https://pf4-release-notes.surge.sh/documentation/react/notes/ and https://pf4-release-notes.surge.sh/documentation/core/notes/!

**Pull request merged**
