### PR TITLE
docs(spacers): Updates content to align with tokens.

### LINKED ISSUE #4130: Spacers: Update documentation and tokens

### PR DESCRIPTION
**Pull request by edonehoo**
Closes #4130 and followup to https://github.com/patternfly/patternfly-org/pull/4088

### CODE REVIEW

**Comment by edonehoo** [comment]
@andrew-ronaldson @lboehling @kaylachumley I updated most of the content here, but I'm a bit unsure of the "using spacers with text" section. Is that info still the same in principle? For ex, I thought that the spacer to use between text would be global/spacer/gap/group/vertical, but is it just grabbing a spacer that matches the body text size? I started to recreate the images with v6 styling, but wanted to share with y'all before I got too far into that

**Comment by edonehoo** [comment]
@andrew-ronaldson @lboehling @kaylachumley Hi! This is ready for a review when you are 🫨

**Comment by kaylachumley** [comment]
Hey! It's not letting me view the preview link - I'm on VPN and I also tried getting off but no luck @edonehoo

**Comment by edonehoo** [comment]
@kaylachumley hmm maybe try incognito? it works fine for me, that's odd 🤔 Not sure if it'll help, but I'll pull in v6 branch updates to see if that fixes it for you

**Review by andrew-ronaldson — APPROVED** [review]
I appreciate the updated visuals! Thanks

**Pull request merged**
