### PR TITLE
Capitalization page edits in UX writing style guide

### LINKED ISSUE #2131: Clarify capitalization guidance in UX writing style guide
Link: https://www.patternfly.org/v4/design-guidelines/content/capitalization

Nav items in title case, but everything else in sentence case (dropdown menu items; action menu items, etc.). Capitalizing proper nouns is part of sentence case and title case rules.

### PR DESCRIPTION
**Pull request by abigaeljamie**
Closes #2131

### CODE REVIEW

**Comment by abigaeljamie** [comment]
@bmignano , I updated the capitalization page a bit more so that it reflects what we talked about (and what folks in content-help weighed in on). Let me know if that looks good to you :) In the preview link, it's under Capitalization > UX writing.

**Comment by mmenestr** [comment]
Looks good! My only comment is that the second picture's spacing is off in the page header. There's too much space between the header and the masthead. This could be easily fixed by just adding breadcrumbs in between, or pushing up the page content!
image

**Comment by bmignano** [comment]
Looks good to me, @abigaeljamie !

**Review by bmignano — DISMISSED** [review]

**Comment by abigaeljamie** [comment]
I added a breadcrumb to the image. Thanks, @mmenestr !

**Comment by abigaeljamie** [comment]
@mmenestr I added some content to the "Capitalization across Red Hat UIs" section to communicate the flexibility of the guidelines. The section's intro copy was tweaked, and some new copy was added below the image in that section. Let me know what you think! If it looks good to you, then this can be merged.

**Review by mmenestr — APPROVED** [review]

**Comment by mmenestr** [comment]
Looks great - merging!

**Pull request merged**
