### PR TITLE
Updates to Horizontal and Vertical Nav Pattern

### PR DESCRIPTION
**Pull request by dlabrecq**
Cherry-picked and squashed sjcox's commits for #262.

Revised broken jump to links and added link for masthead design as well
Added vertical nav masthead design and relevant image assets
Added Horizontal nav masthead designs which includes addition of image
assets

### CODE REVIEW

**Comment by dlabrecq** [comment]
@sjcox-rh and @LHinson please review.

**Comment by LHinson** [comment]
thank you @dlabrecq for the extra help here while we learn... 

Is there any way for me to preview this or is the only way to review via the files changed tab? If not, looks good to me from what I can tell. 

Another question, are we doing 1 or 2 reviews on site updates?

**Comment by dlabrecq** [comment]
We still do two reviews, unless it's very simple. (In this case, 8 files have changed.) I can look to see if it's technically correct (e.g., the jump-to links work), but don't know if anything was missed in the design -- that's why I tagged you.

Unfortunately, the "files changed" tab is all that's available here. Unless you want to download (via the "command line instructions" above) and build? That's how I reviewed SJ's changes previously. Other than that, we could jump on Bluejeans and view the desktop together?

**Comment by sjcox-rh** [comment]
@dlabrecq Thank you so so much.  I feel terrible you had to do this, hopefully this won't happen next time :[  I owe you!

Also, checked everything and it all looks good on my end.  Thanks again!

**Comment by dlabrecq** [comment]
Anytime.

**Pull request merged**
