### PR TITLE
Moved Get in touch content to Community page & updated footer links

### LINKED ISSUE #2232: Merge Get in touch into Community page, update footer
Follow-up to https://github.com/patternfly/patternfly-org/pull/2167

Move the `Get started` page content to the bottom of the `Community` page and remove the `Get started` page.  Also update the links in the site footer to mirror the links currently on the `Get started` page.

### PR DESCRIPTION
**Pull request by evwilkin**
Closes #2232 

This PR:
- Moves content from current Get in touch page to the bottom of the Community page
- Removes the Get in touch page & updates all links to it to point to Community
- Updates the footer links to match the Get in touch contact info

### CODE REVIEW

**Comment by evwilkin** [comment]
@abigaeljamie we were hoping to get your feedback on these changes:
- We've removed the `Get in touch` page and added its content onto the `Community` page.  Currently I've just copied it under what is already there, would love your thoughts on which copy to keep.
- We've updated the links in the footer to match these contact methods currently on the `Get in touch` page, but noticed the footer heading is slightly different at `Stay in touch` - thoughts on if one of the headings should be updated so these match?

**Review by abigaeljamie — CHANGES_REQUESTED** [review]
Thanks, @evwilkin ! I like the idea of having the "get in touch" info here on the Community page. 

I'm thinking we can keep the existing copy (with a small tweak) and then add the contact links underneath. So we won't have the "Get in touch" heading or subcopy. Example: 

## Let's keep growing 
The PatternFly community is never finished growing, and we want to keep it that way. Feel free to reach out whenever — we’re always open. 

Chat with us link
(Slack) 

Ask a question 
(Forum) 

Stay in the loop 
(Mailing list) 

Read the latest 
(PatternFly Medium) 

Is there any way to add Twitter in there? I know the 4 links are balanced, but if we could add Twitter, that'd be cool!

**Comment by evwilkin** [comment]
@abigaeljamie thanks for the feedback, I've made the suggested changes:
- https://patternfly-org-pr-2244-v4.surge.sh/v4

**Review by redallen — APPROVED** [review]

**Review by mcarrano — APPROVED** [review]
Looks good @evwilkin !

**Pull request merged**
