### PR TITLE
Bumped version number to 3.5.1

### PR DESCRIPTION
**Pull request by dlabrecq**
@dtaylor113, @jeff-phillips-18 and/or @andresgalante please review.

### CODE REVIEW

**Comment by dtaylor113** [comment]
So we have it now that we don't have to check in the 'dist' files, correct?

**Comment by jeff-phillips-18** [comment]
LGTM

**Comment by dlabrecq** [comment]
Currently we don't check in dist files; however, that will likely change soon in order to hot deploy.

**Comment by dtaylor113** [comment]
Ok, LGTM but need to rebase the PR

**Comment by dlabrecq** [comment]
Fixed

**Pull request merged**
