### PR TITLE
Add navigation drawer to patternfly-org

### PR DESCRIPTION
**Pull request by dgutride**
I had to use a specific checkin for angular-patternfly (due to the new version not being released yet).  I can modify that if the release is updated.

### CODE REVIEW

**Comment by dlabrecq** [comment]
Need to resolve the conflicts for a successful merge.

**Comment by dtaylor113** [comment]
Downloaded and ran the Navigational Draw Angular Code example.   
LGTM

**Comment by dtaylor113** [comment]
I just merged another PR, you'll need to rebase.
Thanks,
- Dave

**Comment by dgutride** [comment]
@dlabrecq @dtaylor113  - this branch should be up to date again

**Pull request merged**
