### PR TITLE
PTNFLY-1570 Inserting full page example for List View.

### PR DESCRIPTION
**Pull request by cardosogabriel**

### CODE REVIEW

**Comment by cardosogabriel** [comment]
@dlabrecq , this PR depends on this one from patternfly: https://github.com/patternfly/patternfly/pull/370

**Comment by dlabrecq** [comment]
Please hold off on merging this. Need to test if this will break the build or pf.org without the dependency.

We may need to change the patternfly dependency in bower.json to use the commit generated by #370.

**Comment by cardosogabriel** [comment]
#370 was merged.

**Comment by dlabrecq** [comment]
Can you please change the patternfly dependency in bower.json depend on the commit for #370? After ensuring this repo builds and runs locally, we should be good to go.

**Comment by cardosogabriel** [comment]
Dependency updated, with the help of @jeff-phillips-18  :)

**Comment by dlabrecq** [comment]
Built/ran your repo and the changes look good. Unfortunately, we can't merge this right now.

The problem is that Travis won't successfully build because there are too many dependency changes in the latest patternfly. When running bower install, I have to manually select each dependency version because angular-patternfly also uses patternfly, bootstrap-datepicker, bootstrap-select, bootstrap-touchspin, datatables-colreorder, font-awesome and moment.

We could add a temporary "resolutions" section to bower.json or wait until patternfly is released next release, next Wednesday. For example:

"resolutions": {
   "patternfly" : "#0ecf5ee86846bd1498232b3a724f1dccf2518d20",
    "bootstrap-datepicker": "~3.1.1",
    ...
  }

In the mean time, I need to enable Travis to build PRs. This would have showed a Travis build failure. If we Travis cannot build, it also won't be able to push the compiled website to OpenShift.

**Comment by cardosogabriel** [comment]
Ok. So does this mean that we need to wait to patternfly to release an update, then we could merge this one?

**Comment by dlabrecq** [comment]
At this point, I'm thinking we should wait until the release is cut on Wednesday. Right now, the Travis build would most likely fail and website won't be updated until the build is fixed. Adding a resolutions section to bower.json should work, but that would only be temporary -- we would only end up removing it tomorrow/Wednesday.

If you want to remove the commit dependency, it should be ready to merge once patternfly is released? You could do that now or wait until Wednesday when patternfly is released, again.

FYI, we have plans to introduce a Git submodule, which will automatically pull the latest patternfly. We won't need to depend on a specific tag anymore and can finally remove the .../_includes/widgets soft link. Waiting for Brian to return from PTO, but this won't be a problem for long.

**Comment by cardosogabriel** [comment]
Totally fine from me. I'll wait until Wednesday and send a new update.
Very nice this automation module. Thanks!

**Comment by dlabrecq** [comment]
FYI, we cut a new release of patternfly. If you want to remove your dependency changes, it should be ready for a merge.

**Comment by cardosogabriel** [comment]
Great, I rebased and removed the dependency changes, should be good to merge.

**Comment by dlabrecq** [comment]
Thanks for being so patient.

**Pull request merged**
