### PR TITLE
fix(secondary-tabs): refactor the secondary tabs into nested structure

### PR DESCRIPTION
**Pull request by dabeng**
This PR is targeted to fix [issue](https://github.com/patternfly/patternfly/issues/905).

Please review the [Demo](https://rawgit.com/dabeng/patternfly-org/sec-tabs-dist/_site/pattern-library/widgets/#tabs).

### CODE REVIEW

**Comment by mcarrano** [comment]
@dabeng @jgiardino I tried to follow the discussion of this in the React repo, but have to admit to having a hard time understanding what we are changing and why. Can someone please give a quick summary? I would also like @andresgalante to review.

If we are changing the code in the PF core repo, should a PR be sent against the PatternFly repo or the website? Looks like this PR is no change the example on the website? @LHinson FYI

**Comment by LHinson** [comment]
I think this is meant to be a change against core (patternfly-patternfly) vs against patternfly-org.

**Comment by jgiardino** [comment]
@mcarrano We should only need a change to the css files in patternfly core for this and can close this PR. 

The way the css is currently written is tightly coupled with how the html is structured. But the react component cannot reproduce this html exactly the way the css selectors expect it to be. We don't need to change the current html. We only need to add an additional class to the existing styles for the secondary navigation so that we can apply those styles by adding this class to the react component.

I added comments to this PR to describe the changes that we need: https://github.com/patternfly/patternfly/pull/906

**Comment by dabeng** [comment]
Hi @mcarrano, the quick summary is shown in the following picture. Could you tell me which is your favorite "secondary tabs"?
screen shot 2018-01-12 at 1 31 16 pm

**Comment by mcarrano** [comment]
@dabeng Nesting the tabs like this was not what was intended. I could see where this may be useful, but to me it becomes more like a nav bar and I don't think we would want to couple the tabs that way unless a specific application is calling for this design.

**Comment by LHinson** [comment]
I'm going to close this PR as changes should be introduced to core. Thanks!

**Pull request closed without merging**
