### PR TITLE
add versions page with release notes

### LINKED ISSUE #1211: Add PatternFly 4 version information and release notes to patternfly.org
The latest release notes and version information for the following packages should be available with the code documentation.

Release notes can be a running log (prepended to with each milestone release).  We also need to make sure we can quickly show which versions the current documentation refers to.

For instance - the following NPM package information is necessary for the @patternfly packages that ship together:
@patternfly/patternfly: 2.8.2
@patternfly/react-core: 3.34.0
@patternfly/react-styles: 3.2.3
@patternfly/react-tokens: 2.5.3
@patternfly/react-table:2.9.0
@patternfly/react-charts: 4.0.1
@patternfly/react-inline-edit-extension: 2.5.0

### PR DESCRIPTION
**Pull request by redallen**
Add versions page like [Bootstrap's](https://getbootstrap.com/docs/versions/). Add support for building older `RC2` and `RC2.1` versions. Add a release notes page.

Closes #1211

### CODE REVIEW

**Comment by matthewcarleton** [comment]
@redallen is it possible to see a demo of this?

**Comment by redallen** [comment]
@matthewcarleton Not yet, but soon™ I'll have it in staging.

**Comment by redallen** [comment]
@matthewcarleton A demo is now deployed at staging.patternfly.org.

**Comment by redallen** [comment]
Closed in #1564, to be released in next version.

**Pull request closed without merging**
