### PR TITLE
docs(font): added docs for red hat font update to 4.0.2

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly-org/issues/2762

--

This is a rough draft. @mcarrano @mceledonia @abigaeljamie please review the content and let me know what you think.

### CODE REVIEW

**Review by evwilkin — DISMISSED** [review]
LGTM

**Review by mcarrano — APPROVED** [review]
This looks great. Thanks for writing this up @mcoker !

**Review by evwilkin — APPROVED** [review]
LGTM 👍

**Comment by nicolethoen** [comment]
I merged and realized @abigaeljamie had not reviewed - I can absolutely open a follow up PR after @abigaeljamie gives her thoughts!

**Comment by abigaeljamie** [comment]
Haha, no worries @nicolethoen ! I jumped in now to give it a quick skim, and nothing stood out to me as areas that needed to be changed, so we should be all set 👍 Thanks!

**Pull request merged**
