### PR TITLE
Redirecting old "patterns" path to "pattern-library"

### PR DESCRIPTION
**Pull request by dlabrecq**

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
@dlabrecq Now that the site is live, I think we should be reviewing PRs. Do you agree?

**Comment by dlabrecq** [comment]
That's fine. Trying to get this ready for today's celebration

**Comment by jeff-phillips-18** [comment]
@dlabrecq OK, I'll give you a one day reprieve  :)

**Comment by dlabrecq** [comment]
:)

**Pull request merged**
