### PR TITLE
Added a Dockerfile to support site development using docker

### PR DESCRIPTION
**Pull request by bleathem**
See the README for instructions on using Docker to develop the site

### CODE REVIEW

**Comment by cliffpyles** [comment]
Tested `docker:run`, `docker:build`, and the live reload.

Worked great for me. 👍

**Comment by bleathem** [comment]
Travis is failing because the patternfly-eng-release script is looking to execute `npm run build`:
```
npm ERR! Linux 4.11.6-041106-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.8.4/bin/node" "/home/travis/.nvm/versions/node/v4.8.4/bin/npm" "run" "build"
npm ERR! node v4.8.4
npm ERR! npm v3.10.10
npm ERR! missing script: build
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR! /home/travis/build/patternfly/patternfly-org/npm-debug.log
...
The command "sh -x ./node_modules/patternfly-eng-release/scripts/_build.sh -o" exited with 1.
```

The install, build, and deployment are handled elsewhere in the travis config file.  I propose we remove the reference to the release script.

Thoughts @dlabrecq ?

**Comment by dlabrecq** [comment]
I've updated the patternfly-eng-release script and will bump the version in patternfly-org.

The build script executes 'npm run' to see if there is a 'build' target and docker:build matches. I've ensured that the script will find 'build' and not 'docker:build'. The script should now run 'grunt build' for patternfly-org, instead.

**Comment by bleathem** [comment]
Thanks @dlabrecq !

**Pull request merged**
