### PR TITLE
Release 2021.14 highlinghts

### PR DESCRIPTION
**Pull request by mcarrano**
Adds release highlights for the 2021.14 release.

### CODE REVIEW

**Review by nicolethoen — COMMENTED** [review]
I think it's great, but I think it is missing the new (beta) Text Input Group component, which I am personally very excited about. I think you should include it and use any presentations of this document to reiterate how composable solutions give consumers so much more flexibility.

**Review by evwilkin — DISMISSED** [review]
LGTM pending Nicole's feedback

**Comment by mcarrano** [comment]
@nicolethoen good catch regarding the Text input group. I've added that. Let me know if you want to say any more about it.

**Review by evwilkin — APPROVED** [review]
LGTM

**Review by nicolethoen — APPROVED** [review]

**Pull request merged**
