### PR TITLE
Adding search input guidelines

### LINKED ISSUE #1960: Create documentation for Search input
Search input basically works like "control+F". 
Describe how it's different from a basic filter, and give examples of usage + images.

**Original design issue with mocks:** https://github.com/patternfly/patternfly/issues/3151
**Mocks:** https://marvelapp.com/prototype/e9ge7g7/screen/69349151

### PR DESCRIPTION
**Pull request by gdoyle1**
Added search input design guidelines

Fixes #1960

### CODE REVIEW

**Comment by mmenestr** [comment]
@gdoyle1 You deleted one instance of the filtering specifics but not the other hahah gotta do that! Also I just realized it would be good to link to the filter documentation when you mention it in the first line! After that it should be good to go!

**Comment by gdoyle1** [comment]
@mmenestr haha woops!!! just fixed it and added the link

**Review by mmenestr — APPROVED** [review]

**Comment by mmenestr** [comment]
Just need @redallen to double check the file structure and then should be good to merge!

**Review by redallen — APPROVED** [review]
LGTM!

**Pull request merged**
