### PR TITLE
PTNFLY-1803 Color Palette Updates.

### PR DESCRIPTION
**Pull request by cardosogabriel**
- Added color files in a new assets/file folder
- Updated text
- Added Last Update for files.

### CODE REVIEW

**Comment by LHinson** [comment]
LGTM @cardosogabriel 

Is this automatic last updated date something you know how to do?

**Comment by bdellasc** [comment]
No - I just know that the code exists somewhere ;-)

**Comment by LHinson** [comment]
@kybaker do you know anything about this "last updated" code being automatic?

**Comment by bdellasc** [comment]
I think to Gabriel's point, let's see how often it gets updated. It's
probably fine as a manual update for now. It was really just a curiosity
question I had...

**Comment by LHinson** [comment]
+1 sounds good @bdellasc

**Pull request merged**
