### PR TITLE
Some patterns missing from Patterns Overview page

### PR DESCRIPTION
**Pull request by zhutaoredhat**
Updated the patterns missing from Patterns Overview page
https://github.com/patternfly/patternfly-org/issues/166

### CODE REVIEW

**Comment by mcarrano** [comment]
Seems that I cannot preview this in GitHib.  The images do not display. @LHinson or @bleathem do you know anything about how this page is built?  Should I be able to preview this prior to merging?  If not, perhaps we should stage the site before making these changes to the live code base.

**Comment by LHinson** [comment]
@zhutaoredhat can you provide some screenshots of these changes for us to review?

**Comment by zhutaoredhat** [comment]
​Hi @LHinson ,
   Is there something wrong with my operation？All the images do not display?
   These are the thumbnails I updated. https://docs.google.com/document/d/1Zly9Yyz5f00yerFhrnPTrsApaxl-s81mTzhmeTe2bwc/edit#heading=h.ajfddn5mhnft

images-part
code-changed-part

**Comment by LHinson** [comment]
We can see that @zhutaoredhat however we cannot see a preview of how it would display on the page. Do you have a build of the site locally? If so, I was going to see if you could screen cap that. If not, here is some instructions on how to do so: https://docs.google.com/document/d/1p74X-RrSVVdqZ-63lnuIIIHPe6gNPWIw1Fi2l7qYoWE/edit

**Comment by zhutaoredhat** [comment]
Ohoh，got it~ I didn't built the site locally~
I will try it. Please check all the thumbnail images in the google
document~
https://docs.google.com/document/d/1Zly9Yyz5f00yerFhrnPTrsApaxl-s81mTzhmeTe2bwc/edit#heading=h.ajfddn5mhnft

**Comment by david-martin** [comment]
@zhutaoredhat Would it make sense to remove the Dashboard Card as well, given that it will be the 'Base Card' in the Cards section?

https://github.com/patternfly/patternfly-org/blame/40aee1c67d03946eab1be383d5fb97982f8ae700/source/pattern-library/index.md#L151-L158

**Comment by zhutaoredhat** [comment]
Hi @LHinson @mcarrano  I still working on this issue, but met some problems to setup a local environment for PatternFly.org.
 It didn't be solve right now and will ask other people around me.

**Comment by mcarrano** [comment]
@bleathem Can you look at @zhutaoredhat 's comment above and provide some help here? The goal is to be able to preview this before we just merge the PR. Thx.

**Comment by bleathem** [comment]
@zhutaoredhat have you run `bundle install` prior to running the grunt build?

**Comment by junezhang** [comment]
@bleathem if we run "bundle install" we can get the version of jekyll is v3.3.0. 
In this [instruction](https://docs.google.com/document/d/1p74X-RrSVVdqZ-63lnuIIIHPe6gNPWIw1Fi2l7qYoWE/edit), it aims to install the version 2.5.3 of jekyll.
Could I know which version is our recommendation?

**Comment by zhutaoredhat** [comment]
@david-martin Sure, I will remove it.

**Comment by zhutaoredhat** [comment]
@bleathem Hi Brain, It was still failed. @dabeng said he run successful and will help me to continue it. Great thanks~

**Comment by bleathem** [comment]
@junezhang that google doc is out of date.  The version specified by the bundle install is the correct one.

**Comment by bleathem** [comment]
To unblock this review, I've staged this branch for review here:
https://bleathem.github.io/patternfly-org/pattern-library/

cc: @mcarrano @zhutaoredhat

**Comment by mcarrano** [comment]
Thanks, @bleathem .  In looking at this, there are a couple of issues to address.  Looks like we are missing thumbnails for Data Input and Canvas View. Also, in the Cards section, we have a gap between the utilization bar and utilization trend cards. @zhutaoredhat can you please take a look?

**Comment by zhutaoredhat** [comment]
@mcarrano I have a question about the all  design mockups in Patternfly.org are sync from Patternfly-design in github?

**Comment by zhutaoredhat** [comment]
@bleathem  Great thanks to your branch review, that's very useful to me.
@mcarrano Could you help me review the fixed overview page please? #421
@mcarrano @LHinson All the thumbnails are 200px*200px right now, they looks a little blurred on Retina Screen. Could we update them to 400*400px and fix the size still 200px*200px by CSS.

By the way, I have a question about whether all the design images in Patternfly.org are sync from Patternfly-design of github.

**Comment by mcarrano** [comment]
@bleathem what needs to happen to see Tao's latest commit? Doesn't look like those fixes are showing up just yet.

@zhutaoredhat @LHinson regarding the resolution of the thumbnail images, do you have an example of where that's a problem? I'm either not seeing this or not so sensitive to the difference. My only concern with increasing the image resolution would be that the page will be slower to load. Not sure I understand the question about sync between patternfly-design and patternfly-org.

**Comment by zhutaoredhat** [comment]
@mcarrano Sorry, I had pulled a new request.https://github.com/patternfly/patternfly-org/pull/421

**Comment by bleathem** [comment]
I've updated the site stage available at:
https://bleathem.github.io/patternfly-org/pattern-library/

**Comment by zhutaoredhat** [comment]
Sorry Brain, the site stage is not the latest one. Could you help run
https://github.com/patternfly/patternfly-org/pull/421?

**Comment by mcarrano** [comment]
This PR is superceded by #421 I'm closing this out to avoid confusion.

**Pull request closed without merging**
