### PR TITLE
Slider component guidelines

### PR DESCRIPTION
**Pull request by wolfeallison**
closes: #3201

### CODE REVIEW

**Comment by mmenestr** [comment]
@wolfeallison Looks good, but you need to remove the colons after each header! Also it looks like your branch is up to date with main - so have to fix that too! Not sure why that keeps happening

**Comment by wolfeallison** [comment]
@mmenestr Just removed the colons! Do I not want the branch up to date with main? I've been updating it every time so that's my bad if I shouldn't

**Comment by mmenestr** [comment]
@wolfeallison you do want to make sure it's up to date when you first create the branch, so not sure what's happening here.
@nicolethoen or @evwilkin, what should she do? Update with merge commit, or update with rebase?

**Comment by nicolethoen** [comment]
I don't think you've done anything wrong. It seems that github is just letting you know that other people have merged PRs to org since the last time you updated your issue's branch. There are two ways to fix it:
- click the 'Update branch' button and follow the steps to updating it. I'd only recommend that if you don't think you'll be making any more updates to your branch yourself.
- if you are going to make updates to your branch in response to PR feedback, then make the updates, add them and commit them. Then `git fetch upstream && git rebase upstream/main` then you'll push your latest changes and the update from upstream with `git push -f origin <branch name`

Feel free to ping me with any questions :)

**Comment by mmenestr** [comment]
Thanks @nicolethoen !! @wolfeallison I think it's save to do what's in the first bullet then because it looks good to go other than this merge issue :)

**Comment by wolfeallison** [comment]
@nicolethoen Thank you!!
@mmenestr Just clicked 'update branch' - let me know if it doesn't work!

**Review by mmenestr — APPROVED** [review]

**Pull request merged**
