### PR TITLE
added empty state docs

### PR DESCRIPTION
**Pull request by stacymcauliffe**

### CODE REVIEW

**Comment by stacymcauliffe** [comment]
@mcarrano - updated the images and removed the variations section of this doc

**Comment by mcarrano** [comment]
@stacymcauliffe your latest changes look so much better! I like seeing the different empty state examples in context. Just one question - is there a reason we would use a card in the background or not? I'm seeing that in the last example (success) you are placing the empty state inside of a card with a white background and in other cases you do not. What's the difference?

**Comment by stacymcauliffe** [comment]
Good question @mcarrano - I guess I was thinking that the success message might be displayed on whatever the user just finished interacting with.

**Comment by mcarrano** [comment]
Yes, I guess that's true @stacymcauliffe . Maybe instead of this include a completion screen as in my Wizard doc here: https://docs.google.com/document/d/1rgAXIBFGfeDwHTjVvHvKzD5Zqtro6kQkpt3PJvK0kkg/edit?usp=sharing  I can send that image.

**Comment by stacymcauliffe** [comment]
Creating new PR in master

**Pull request closed without merging**
