### PR TITLE
card page changes

### PR DESCRIPTION
**Pull request by abigaeljamie**
Closes [1786](https://github.com/patternfly/patternfly-org/issues/1786)
Closes [1804](https://github.com/patternfly/patternfly-org/issues/1804)

### CODE REVIEW

**Comment by abigaeljamie** [comment]
Thanks for the feedback! I replaced the copy so that we have the Compact and Standard card types, and I replaced all the images from @mmenestr . The only thing I need is one more image (it appears broken in the preview because I deleted it). @gdoyle1 , do you mind sending it to me again? You sent it to me a few weeks back in Slack, but Slack erased it. It's the image that shows the sticky bottom toolbar.

**Comment by gdoyle1** [comment]
@abigaeljamie here's the img!
Card view with sticky bottom toolbar - desktop

**Comment by abigaeljamie** [comment]
Thanks, @mmenestr and @gdoyle1 ! I added the image. If this all looks good to @mcarrano , then we should be good to go!

**Comment by abigaeljamie** [comment]
Thanks, team! Are one of you able to merge? @mmenestr / @mcarrano

**Pull request merged**
