### PR TITLE
chore: fixed fonts and deleted unnecessary classes

### PR DESCRIPTION
**Pull request by ashley-o0o**
Updated font families and removed unnecessary classes.

Closes https://github.com/patternfly/patternfly-org/issues/3537

### CODE REVIEW

**Comment by nicolethoen** [comment]
Is there an open issue this is referencing that you can connect to this issue? 
You could edit initial comment on this PR to additionally say `Closes: [copy/paste the url of the issue it addresses]`

**Comment by ashley-o0o** [comment]
Closes: [#3537](https://github.com/patternfly/patternfly-org/issues/3537)

**Review by nicolethoen — APPROVED** [review]

**Review by mcoker — COMMENTED** [review]
This looks great to me! One thing I'm noticing is that there are some headings that have the wrong font family - https://patternfly-org-pr-3548-v4.surge.sh/v4/design-foundations/colors#primary-colors

Here's the current v4 docs to compare - https://www.patternfly.org/v4/guidelines/colors#primary-colors

Looks like it may be with `--pf-v5-c-content--heading--FontFamily` not working?

**Comment by nicolethoen** [comment]
@mcoker is that something we can fix in org? or is the root of that var not working something originating somewhere else?

**Comment by mcoker** [comment]
@nicolethoen it looks the documentation framework package in this PR is on core [`^5.0.0-alpha.46`](https://github.com/ashley-o0o/patternfly-org/blob/7eded2969b48b703c735b3848daa36707b692571/packages/documentation-framework/package.json#L87) and the change from `--pf-global--FontFamily--heading--sans-serif` to `--pf-global--FontFamily--heading` (the style that isn't working) was introduced in [`v5.0.0-alpha.57`](https://github.com/patternfly/patternfly/releases/tag/prerelease-v5.0.0-alpha.57).

The docs framework on v5 is currently on [`^5.0.0-alpha.64`](https://github.com/patternfly/patternfly-org/blob/a31454d8349dec1c5f8b5a15a7121b7b2d9435b2/packages/documentation-framework/package.json#L87) so rebasing this PR from v5 should fix it. I tried verifying locally but couldn't get the build to work after rebasing. An aside, I can't get v5 to build on its own, either.

**Pull request merged**
