### PR TITLE
Compact tree view guide

### LINKED ISSUE #2538: Add to tree view guidelines with enhancements
Want to add mentions of new tree view variation to the guidelines.
I believe this is called "Compact tree view" where you have the ability to collapse sections?

Refer to this design issue for details: https://github.com/patternfly/patternfly-design/issues/1043
See marvel here: https://marvelapp.com/prototype/73043j4/screen/80030545
Core: https://github.com/patternfly/patternfly/issues/4177

### PR DESCRIPTION
**Pull request by doruskova**
Adding guidelines for a Compact tree view.

Closes #2538

### CODE REVIEW

**Comment by doruskova** [comment]
@mcoker Hey Michael! Could you help us? Do you know what's wrong with the build? Did I do something wrong?

**Comment by mcoker** [comment]
@doruskova your update looks great! The problem looks related to something else. I have a PR here that will hopefully fix it https://github.com/patternfly/patternfly-org/issues/2765

**Comment by mcoker** [comment]
@doruskova should be good now!

**Comment by doruskova** [comment]
@mmenestr It's working!
@mcoker Thank you so much!

**Review by nicolethoen — APPROVED** [review]

**Pull request merged**
