### PR TITLE
WIP: new download page for patternfly.org

### PR DESCRIPTION
**Pull request by dabeng**
This is the initial PR for creating download page of patternfly.org site.

@Mgranfie @LHinson @deernano please review the [demo page](https://rawgit.com/dabeng/patternfly-org/download-page-dist/_site/download/index.html).

### CODE REVIEW

**Comment by LHinson** [comment]
* Editor help on intro text needed.
* The icons for the repos are redundant therefore do not help me discern the difference between the repos nor does it provide visual interest
* Repo descriptions crafted and updated 
* A description of the tools section would be nice. Are these tools that we recommend or use? Should provide clarification for the reason that we presenting this? 
* Should fonts and icons be here? They are represented under styles. We do have custom patternfly icons in addition to font awesome icons, that should be represented, if this remains. 

@Mgranfie @deernano

**Comment by Mgranfie** [comment]
Thanks @dabeng this looks great. A few pieces of feedback...

1. "Choose your environment.. good things like tolls", should be "tools"
2. @LHinson I agree that the icons for the repos aren't super valuable, they do act to reinforce PF, Angular and React,so that at a glance there is some differentiation and also adds some visual interest to the page. Let's also ask the visual designer on this for input here.
3. Agreed that the descriptions for the repos can use assistance. Many of these match what we have on the repos today. Maybe an across the board story to align the updates would be useful?
4. Agree a quick desc on the tools would be nice
5. Font and icons were located here as we had feedback that there is an expectation by the users to find them here... Yes, let's add the custom icons here.

**Comment by Mgranfie** [comment]
@dabeng I also provided some feedback in the Google doc that Melody created.
https://docs.google.com/a/redhat.com/document/d/1grCgtpRDyrrof7yu9tZ4kY7rp1zo0plN7hM4aRFsa68/edit?usp=sharing

**Comment by dgutride** [comment]
Closing due to lack of movement - please reopen if this is a necessary improvement.

**Pull request closed without merging**
