### PR TITLE
Added "what's new" sticky for heat map: hover for scalability

### PR DESCRIPTION
**Pull request by dlabrecq**

### CODE REVIEW

**Comment by dlabrecq** [comment]
@LHinson please review

**Comment by LHinson** [comment]
Is this for the home page? I've been updating the "sticky" blog post via word press. @dlabrecq

**Comment by dlabrecq** [comment]
Yes. The URL (https://www.patternfly.org/whats-new/) in the story references the home page.

**Comment by dlabrecq** [comment]
@LHinson I added missing what's new updates from blog per our discussion.

**Comment by LHinson** [comment]
Great, thanks @dlabrecq! LGTM

**Comment by LHinson** [comment]
I guess we need one more review to merge? Will one of you help? @dtaylor113 @jeff-phillips-18 @priley86

**Comment by dlabrecq** [comment]
This was merged a couple days ago.

**Pull request merged**
