### PR TITLE
Fix the thumbnails bugs on overview page

### PR DESCRIPTION
**Pull request by zhutaoredhat**
1.Fixed missing thumbnails for Data Input and Canvas View.
2.Fixed in the Cards section, there is a gap between the utilization
bar and utilization trend cards.
3.remove the Dashboard Card (Base)
https://github.com/patternfly/patternfly-org/pull/417#issuecomment-30876
9835

### CODE REVIEW

**Comment by zhutaoredhat** [comment]
@LHinson @mcarrano could you help me to review and merge it please?

**Comment by mcarrano** [comment]
@zhutaoredhat I am a little confused by this. Can you explain the difference between this PR and #417 ? Should one of these be closed? Sorry that I have not paid attention to this sooner but would like to resolve and merge, if possible.

**Comment by zhutaoredhat** [comment]
@mcarrano #421 is the latest one and all the changes are base on #417 . The differences  between #421 and #417 are:
 1.Fixed missing thumbnails for Data Input and Canvas View.
2.Fixed in the Cards section, there is a gap between the utilization
bar and utilization trend cards.
3.remove the Dashboard Card (Base)

I think we can merge #421 directly, the #417 will be merged too.
If that is not make sense, we should merge #417 firstly, than merge #421.
I'm very sorry that I don't have much experience in this matter.

**Comment by mcarrano** [comment]
So does #421 then have all of the changes, meaning everything from #417 and additional changes listed above? In that case, I think we should just close #417 and move forward with validating and merging #421.  Let me know if there is a reason this does not work @zhutaoredhat

**Comment by zhutaoredhat** [comment]
@mcarrano As we discussed, #421 is base on #417,  If merge 421 with all the updates, than we can close 417~

**Comment by bleathem** [comment]
I've staged this branch here:
https://bleathem.github.io/patternfly-org/

**Comment by zhutaoredhat** [comment]
@bleathem Great, Thank you~

**Comment by mcarrano** [comment]
Thanks, @bleathem ! Looks good to me. @zhutaoredhat did you verify that all your changes are in? I will be on PTO, but @LHinson , perhaps you can merge if Tao gives the go ahead.

**Comment by LHinson** [comment]
Yep, just tag me @zhutaoredhat and I'll merge! Thanks all!

**Comment by zhutaoredhat** [comment]
@mcarrano @LHinson Looks good to me too. Please merge it~

**Pull request merged**
