### PR TITLE
Replace Switch with Select

### LINKED ISSUE #850: Update to Nav to show Dropdown
Right now the left nav does not display a dropdown, it shows a toggle, and it should to budget for future frameworks that may live there. See component wireframe: 

Screen Shot 2019-04-25 at 3 02 38 PM

### PR DESCRIPTION
**Pull request by christiemolloy**
Close #850 

@jschuler or @redallen could one of you help direct the selects to the routes, I'm not sure how to 
 :)

Screen Shot 2019-05-15 at 11 33 59 AM

Screen Shot 2019-05-15 at 11 34 05 AM

### CODE REVIEW

**Comment by jschuler** [comment]
@christiemolloy I can update the PR with the routing functionality

**Comment by jschuler** [comment]
Routing should work now @christiemolloy

**Comment by christiemolloy** [comment]
thank you @jschuler !!!

**Comment by christiemolloy** [comment]
@mindreeper2420 theres no check on both of them now, do you think thats ok. If so I think you can merge :)

**Pull request merged**
