### PR TITLE
Fixed Design guidelines - Round 2

### PR DESCRIPTION
**Pull request by mmenestr**
Second round of fixes for design guidelines
(fixes issue #1199 )

### CODE REVIEW

**Comment by mcarrano** [comment]
@jschuler Looks like merging is blocked waiting for travis-ci checks to complete. Any idea what the problem is?

**Comment by redallen** [comment]
@mcarrano There are merge conflicts now.

**Comment by mcarrano** [comment]
@mmenestr @gdoyle1 looks like some of these changes might have been made against stale versions of files. See conflicting files above. If you are in Boston tomorrow, we can work through these issues and figure out how to fix.

**Comment by mmenestr** [comment]
@mcarrano I will be in all day today, let me know when you have time to go over this!

**Pull request merged**
