### PR TITLE
fix(nav): fix sidenav jumping on navigate

### PR DESCRIPTION
**Pull request by redallen**
Quality of life++

### CODE REVIEW

**Review by ddonahue007 — DISMISSED** [review]
LGTM

**Comment by mmenestr** [comment]
Navigation LGTM too, but the footer is all messed up and appears in the middle of all pages? (I know that's not what this PR is concerned with but just wanted to point it out in case)
image

**Comment by redallen** [comment]
@mmenestr I just noticed this too and am working on a fix.

**Comment by redallen** [comment]
Please rereview @ddonahue007 and @mmenestr !

**Pull request merged**
