### PR TITLE
Style order issue

### PR DESCRIPTION
**Pull request by CooperRedhat**
Fixes: #3054

Does fix it as @mcoker suggested, but is it the best way to handle?

### CODE REVIEW

**Comment by jschuler** [comment]
LGTM, client-styles will be replaced by webpack and contain things like patternfly.css etc. So it makes sense to me to have it higher up the load order

**Review by jschuler — DISMISSED** [review]

**Comment by CooperRedhat** [comment]
@mcoker https://patternfly-org-pr-3076-v4.surge.sh/v4 buttons look good and no errors in the console now. I'm not sure if this was a surge specific issue, because I wasn't seeing the same errors locally.

**Review by mcoker — APPROVED** [review]
LGTM! 🚀

**Review by evwilkin — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
