### PR TITLE
Release highlights 2022.13

### PR DESCRIPTION
**Pull request by mcarrano**
Adds highlights for the 2022.13 release.

### CODE REVIEW

**Review by nicolethoen — COMMENTED** [review]
Looks good to me - 

Should we add a highlight about the Select next implementation?

**Comment by mcarrano** [comment]
> Should we add a highlight about the Select next implementation?

Sure. @nicolethoen can you just give me a sentence or two and I'll add it.

**Review by evwilkin — DISMISSED** [review]
LGTM

**Comment by mcarrano** [comment]
@nicolethoen I added a mention of the React-next version of Select. Please take a look and merge if you are good with this. Thanks.

**Review by nicolethoen — APPROVED** [review]

**Pull request merged**
