### PR TITLE
Updated the build to use an up-to-date ruby gem bundle

### PR DESCRIPTION
**Pull request by bleathem**
This PR:
*  Adds a grunt jekyll option to use the 'bundle exec' prefix when running jekyll
* Updates the gems in our Gemfile.lock file
* Updates the README to include bower and bundle install steps

### CODE REVIEW

**Comment by dlabrecq** [comment]
The Travis build is failing due to this error. This is similar to what I was seeing with saas.

Gem::InstallError: rack requires Ruby version >= 2.2.2.

**Comment by bleathem** [comment]
Thanks @dlabrecq.  I've updated the travis.yml file to use a recent ruby version, and the build succeeds.

**Comment by andresgalante** [comment]
if @dlabrecq is ok with it, then I am more than ok with it.

**Comment by dlabrecq** [comment]
LGTM

**Pull request merged**
