### PR TITLE
PTNFLY-1349 Horizontal Navigation Page

### PR DESCRIPTION
**Pull request by cardosogabriel**

### CODE REVIEW

**Comment by dlabrecq** [comment]
LGTM

**Comment by dlabrecq** [comment]
FYI, I removed the source/assets/css/patternfly-site.css file. We don't need to commit generated css for patternfly-org.

**Comment by cardosogabriel** [comment]
Ok, thanks for letting me know ;)

**Comment by dlabrecq** [comment]
FYI, the following style changes broke the images for the vertical navigation example. See issue #172.

.navbar .navbar-brand img { // Overwriting inherited styles from ng-docs.css.
  padding-right: 0;
  height: 10px;
  width: 270px;
  margin: 0;
}

**Pull request merged**
