### PR TITLE
feat(docs): add sketch design training to site

### LINKED ISSUE #1855: Add early support for Sketch design e-training
The creation of a [Sketch design e-training](https://patternflyt-training.thinkific.com/courses/pf-sketch-e-training) is about 95% complete, and this should be hosted on patternfly.org as a resource for the whole design community. We have a design for a landing page that we would like to implement to serve as an introduction to the training, but we would first like to address some quick interim solutions to at least get the training itself out in the open. [Here's what the overall flow will look like](https://marvelapp.com/55dfejd). 

### Here are the items that need to get taken care of for this first launch of the training

- [x] Add linking to [this training](https://patternflyt-training.thinkific.com/courses/pf-sketch-e-training) on the [getting started for designers page](https://www.patternfly.org/v4/get-started/designers) under 'Using the design kit' (screenshot below of what this section should say and how it should look) 
Screen Shot 2020-05-22 at 3 07 34 PM

- [ ] Add a secondary nav item into the getting started > designers flow to [the training](https://patternflyt-training.thinkific.com/courses/pf-sketch-e-training) as well (screenshot below of what this section should say and how it should look) 
Screen Shot 2020-05-22 at 3 07 11 PM

- [ ] Host a PDF version of the cheatsheet asset (required asset for the training) on the site. For right now, the URL doesn't matter, as it will just be externally linkable from the training itself. The user should be able to view and/or download the PDF attached here

[ACrashCourseinSketchProficiency (2).pdf](https://github.com/patternfly/patternfly-org/files/4669964/ACrashCourseinSketchProficiency.2.pdf)

### PR DESCRIPTION
**Pull request by evwilkin**
Closes #1855 

This PR adds the Sketch design training to the training section of the website.

### CODE REVIEW

**Comment by evwilkin** [comment]
@maryshak1996 there's no easy way to add a sidenav item that links to an external site - each nav item is created from an associated markdown file, so based on that (and to keep the training section consistent) I've added a Design training page here:
- https://patternfly-org-pr-2671-v4.surge.sh/v4/training/design/

LMK what you think, and please let me know how we should customize the text on the training card - you can reference any of the [other training sections](https://patternfly-org-pr-2671-v4.surge.sh/v4/training/html) to see some examples.

**Comment by maryshak1996** [comment]
@evwilkin thanks for putting this together! using the styles and such that you've already established, I've put together this mock up of how we could use the cards to section the different 'chapters' of the training out, like you've done with the katacodas. 
Prototype: https://marvelapp.com/prototype/h2cj7he
Note: I've added hotspot for each card and hint text to where they should navigate the user to. 
Let me know if there's any questions or if any of this doesn't fit within the structure that you've got for building these.

**Comment by evwilkin** [comment]
@maryshak1996 thanks for working on this!

The other training pages link out to different Katacoda trainings, which are each self-contained trainings on different topics.

We can build out the design page as you've mocked up, but it looks like each card links to a different section (chapter) of one training - if additional design trainings are created in the future, how would they fit onto this page?

Let me know what you think - thanks!

**Comment by evwilkin** [comment]
@maryshak1996 hoping to unblock this, can you let me know what you think about [my note above](https://github.com/patternfly/patternfly-org/pull/2671#issuecomment-915536741)?  Looking forward to getting this added to the site, thanks!

**Comment by maryshak1996** [comment]
Hey @evwilkin ! Sorry for this delay here!

> We can build out the design page as you've mocked up, but it looks like each card links to a different section (chapter) of one training - if additional design trainings are created in the future, how would they fit onto this page?

We haven't ever talked about having any other trainings available for designers, so I don't think that we need to think about scalability in that way. So if it's reasonable to have it set up as shown in the mocks that would be great!

**Comment by evwilkin** [comment]
@maryshak1996 updated with your designs, LMK what you think!
- https://patternfly-org-pr-2671-v4.surge.sh/v4/training/design

**Review by maryshak1996 — APPROVED** [review]
Looks fantastic thank you!

**Pull request merged**
