### PR TITLE
Release highlights - 2021.06

### PR DESCRIPTION
**Pull request by mcarrano**
Adding release highlights for the 2021.06 release.

### CODE REVIEW

**Comment by mcarrano** [comment]
@evwilkin @nicolethoen 2021.06 release highlights are ready for review. Do you think I should pull Log Viewer from the highlights given today's meeting? Or does it make sense to keep it here and talk to some of the issues?

**Comment by nicolethoen** [comment]
@mcarrano I think it's definitely worth a conversation with the product teams either way. If the release notes get distributed further beyond the meetings, it may be worth removing it to avoid it getting too much attention?

**Comment by mcarrano** [comment]
@nicolethoen I made some changes to text about the log viewer. Please take another look. Thanks.

**Review by nicolethoen — APPROVED** [review]

**Review by evwilkin — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
