### PR TITLE
Implented the Pattern Status page

### PR DESCRIPTION
**Pull request by bleathem**
The page is staged at:
http://bleathem.github.io/patternfly-org/stage/status-page/pattern-library/

### CODE REVIEW

**Comment by bleathem** [comment]
@mcarrano are you sure the web components work is being discontinued?

**Comment by mcarrano** [comment]
I believe that was what was decided, @bleathem . @LHinson can you confirm this regarding Web Components?

**Comment by LHinson** [comment]
Web Components is not being "discontinued" per say, but it is being put on hold and we will revisit at a much later date to see if it's something that we want to pursue in the future. It will not be part of our roadmap to date. 

The only js implementations that should be visible from the site at this time are: Angular 1, patternfly-ng and patternfly-react. That means we should remove JQuery, Web Componets and CSS Next. 

Also, would it be possible to link the pattern names to the corresponding web page? 

@bleathem @mcarrano

**Comment by mcarrano** [comment]
Thanks for the clarification @LHinson .  My only question is whether we should keep a link for the jQuery implementation. This is essentially the PF Core implementation of HTML/CSS/jQuery found on the test pages, not the jQuery showcase. I think this is useful to reflect components with/without test pages currently.

**Comment by bleathem** [comment]
I've made the pattern names links, dropped and renamed the columns as requested.  I've also updated the stage.

**Pull request closed without merging**
