### PR TITLE
PTNFLY-1586 Card View Page.

### PR DESCRIPTION
**Pull request by cardosogabriel**

### CODE REVIEW

**Comment by cardosogabriel** [comment]
This one doesn't depend on Patternfly updates. Please review.

**Comment by dlabrecq** [comment]
LGTM. I built and ran the changes locally.

**Comment by cardosogabriel** [comment]
Does anybody else need to review or can u merge?

**Comment by dlabrecq** [comment]
We typically like to have two reviews. I'll give a little more time before merging, should someone else want to review?

**Pull request merged**
