### PR TITLE
Update Alerts and Notifications to include Inline alert

### PR DESCRIPTION
**Pull request by mcarrano**
Adds new inline alert variant to existing Alerts and notifications usage guidelines.

Closes: #817

### CODE REVIEW

**Comment by mcarrano** [comment]
@stacymcauliffe Can you please review my updates? They are pretty minor as there is really no functional difference between the existing toast and new line styles. Thanks.

**Comment by mcarrano** [comment]
This feature has been deferred to the June 17 release. Do not merge for now.

**Comment by bdellasc** [comment]
Since the original design story has been closed, here's the link to the updated source file (from May 28) for @mcarrano to generate the new images.

https://drive.google.com/open?id=1MZzqkM8wJITbdU1k80muE_ifiL1EPU2F

**Comment by mcarrano** [comment]
@jschuler @rachael-phillips can this be merged now for the Albatross release? It is done from my perspective. If so, I just need a quick review and approval from you, @stacymcauliffe .

**Pull request merged**
