### PR TITLE
uploaded new illustrations

### LINKED ISSUE #3612: Update All Components view with new illustrations
Some of the illustrations for the All Components view have been reworked by Design to improve consistency. New illustrations need to be uploaded to `patternfly-org`

@smckinno can you add a link to your new files here?

### PR DESCRIPTION
**Pull request by smckinno**
Updating the new component illustrations from last time - aka Round 2

Closes #3612

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]

**Comment by evwilkin** [comment]
@mcarrano @smckinno A few images are no longer needed, and a few have slight different or misspelled names from the existing images (causing new illustrations to be added alongside what already exists):

Remove images:
- alert-group (component was merged into Alert page)
- all-components (no illustration needed)
- chip-group (component was merged into Chip page)
- label-group (component was merged into Label page)

Rename image:
- time-stamp.png should be `timestamp.png` (no dash in component name)
- treeview.png should be `tree-view.png` (missing dash in component name)
- ilnline-edit.png should be `inline-edit.png` (typo)

**Review by evwilkin — CHANGES_REQUESTED** [review]
4 images can be removed and 3 renamed, otherwise looks good - thanks!

**Review by mcarrano — APPROVED** [review]
Looks great. Thanks @smckinno !

**Review by evwilkin — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
