### PR TITLE
Inline edit example for pf-org

### PR DESCRIPTION
**Pull request by amarie401**
## Description

* This PR introduces the inline-edit example to pf-org
Fixes https://github.com/patternfly/patternfly-org/issues/556

## Changes
* `code.md` introduced 

## Rawgit
* [preview here](https://rawgit.com/amarie401/patternfly-org/inline-edit-dist/_site/pattern-library/forms-and-controls/inline-edit/#code)

### CODE REVIEW

**Comment by matthewcarleton** [comment]
@amarie401 ok will do, feel free to ping me once that is resolved if I don't catch it :)

**Comment by dabeng** [comment]
Hi @amarie401 . bootstrap-combobox is not a high-quality jquery plugin. It's very pity that this bug is caused by reinitialization - https://github.com/patternfly/patternfly-org/blob/master/source/assets/js/patternfly-site.js#L5. So I suggest that you can include "inline edit in a form" with the following style:
```html
<h2 id="example-code-1">Tree List View - Single Child Expansion</h2>
<div class="example-pf">
  <iframe src="{{site.baseurl}}/pattern-library/content-views/tree-list-view/tree-list-view-single-child-expansion.html"
          width="100%" height="650px;" scrolling="no" seamless></iframe>
</div>
```

**Comment by amarie401** [comment]
Tried it using the iframe format and still broken.. @dabeng 

screen shot 2018-04-26 at 10 34 46 am

**Comment by dabeng** [comment]
sorry @amarie401 . I can't find iframe tag on your demo page - https://rawgit.com/amarie401/patternfly-org/inline-edit-dist/_site/pattern-library/forms-and-controls/inline-edit/#code

screen shot 2018-04-27 at 9 40 58 am

If you included "inline edit for form" with iframe, it would be like the following picture:
screen shot 2018-04-27 at 9 39 50 am

**Comment by dabeng** [comment]
Hi @amarie401 , sorry for late reply. I think you need to  put forward a PR to patternfly-core repo:
replace this [line](https://github.com/patternfly/patternfly/blob/master/tests/pages/_includes/widgets/forms/inline-edit-for-form.html#L132)
```
$('.combobox').combobox();
```
with 
```
$('select.combobox').combobox();
```

**Comment by amarie401** [comment]
Thank you @dabeng that fixed the issue. I have a PR up for review in core. Please review this [PR](https://github.com/patternfly/patternfly/pull/1048) along with @matthewcarleton. Once that gets merged in then I can update this PR.

**Comment by amarie401** [comment]
The fix in core has been merged and this PR has been updated. This is ready for review :)

**Pull request merged**
