### PR TITLE
Clarify alert documentation

### PR DESCRIPTION
**Pull request by mcarrano**
Clarify alert documentation per issue #1291 . Changes include:
* Clarify that toast alerts must always include a close button (and remove examples that do not).
* Provide more detail on alert colors.

Fixes: #1291

### CODE REVIEW

**Comment by mcarrano** [comment]
@ajacobs21e @Rohoover Can you please review to see if this addresses your concerns? Thanks.

**Comment by ajacobs21e** [comment]
@mcarrano it looks like the toast examples still have some without the dismissible icon. But that could be my github ignorance. Was that image updated?

**Comment by ajacobs21e** [comment]
What do you think about rewriting this

> Close (optional): Dismiss the alert. Note that toast alerts must always have a Close action.

as

Close: Dismiss the alert. Required for toast alerts and optional for inline alerts.

**Comment by mcarrano** [comment]
> @mcarrano it looks like the toast examples still have some without the dismissible icon. But that could be my github ignorance. Was that image updated?

@ajacobs21e do you mean the ones under "Communicating status?" I can fix those.

Like your suggestion for text wording around Close. Will change.

**Comment by ajacobs21e** [comment]
Screen Shot 2019-09-13 at 2 49 16 PM
@mcarrano these examples

**Comment by mcarrano** [comment]
@ajacobs21e It seems like when you preview the file this way, GitHub is not seeing that the image is changed for some reason. It should be showing this:

Screen Shot 2019-09-16 at 2 52 51 PM

**Comment by ajacobs21e** [comment]
Ah, thanks @mcarrano . That's perfect then!

**Comment by mcarrano** [comment]
@vconzola I just made updates to this document to reflect our email conversation earlier this week in the Usage section for Inline Alerts. Please take a look and let me know if this explains better the usage. Thanks.

**Comment by vconzola** [comment]
@mcarrano Looks good. Thanks for clarifying that text.

**Comment by mcarrano** [comment]
@rachael-phillips @jschuler I think this is ready to go. Can one of you give this a final review and approve/merge if you think it's ready?

**Pull request merged**
