### PR TITLE
tooltip chart design guidelines

### LINKED ISSUE #1919: Add documentation for "legend tooltips" to Charts guidelines
Legend tooltips were introduced in release 2020.08. See https://github.com/patternfly/patternfly-react/pull/4371 We should add to Charts documentation here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/charts

### PR DESCRIPTION
**Pull request by mmenestr**
closes #1919

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
@mmenestr I think that the document is fine. The only question I have is whether we should give guidance on what goes inside the tooltip. Is this always in the form shown in this example? Would there be any variations or labeling considerations?

**Comment by mmenestr** [comment]
Yeah I guess we kept it quite broad with " The content of the tooltip could also include any additional information that might be important to show the user." and I'm really not sure @nlcwong do you know? (what can go inside a tooltip and if there are any considerations to take into account)

**Comment by nlcwong** [comment]
LGTM

**Review by mcarrano — APPROVED** [review]
Looks good. Will merge. Thanks @mmenestr

**Pull request merged**
