### PR TITLE
Update to icon guidelines to emphasize ability to use any FA free icon

### LINKED ISSUE #1888: Update Icons page link to additional Font Awesome icons
The icons page contains a link to Font Awesome free icons, but the ask is to update the wording or make it more prominent so that designers & developers don't miss the additional available icons (already distributed through PF) and end up creating custom icons where one may already exist.

### PR DESCRIPTION
**Pull request by mmenestr**
Made a few updates to the icon guidelines text to further emphasize the fact that designers can use any FA free icon offered.

Fixes #1888

### CODE REVIEW

**Comment by mmenestr** [comment]
@mcarrano I think that's a great idea!
This seems to be the current messaging.
image

We could change it to something along these lines:
image

**Comment by evwilkin** [comment]
@mmenestr @mcarrano copy can be updated in this file (below), or feel free to post what the updated text should be here and tag me and I can help with those changes:
- https://github.com/patternfly/patternfly-org/blob/master/packages/v4/src/content/design-guidelines/styles/icons/IconsTable.js#L172-L177

**Comment by mmenestr** [comment]
Thanks @evwilkin! I can make the change if you are both fine with the text: "We couldn't find any icons that matched your search. If none of the icons listed fit your use case, you may use any additional 'fa' icons within Font Awesome's free set."

**Comment by evwilkin** [comment]
@mmenestr that sounds good to me, thanks!

**Comment by mcarrano** [comment]
Me, too!

**Comment by mmenestr** [comment]
@mcarrano @evwilkin updated like we said! Let me know if you want me to make any more edits/additions!

**Pull request merged**
