### PR TITLE
docs(colors): Update content to support tokens.

### LINKED ISSUE #4042: Colors: Update documentation and tokens

### PR DESCRIPTION
**Pull request by edonehoo**
Closes #4042

### CODE REVIEW

**Comment by edonehoo** [comment]
@lboehling @andrew-ronaldson hi! here's a first pass as some updates to the colors page. lmk if that images are too difficult to interpret. I hacked them together in Figma, so I can easily edit/remove the annotations/whatever would make them most helpful. 

@nicolethoen I made a few css updates -- the swatches are aligning weird and the color grabbing still doesn't work, but I think those are the only major things I'm seeing? 

Happy to hear any feedback/ideas for change!

**Comment by andrew-ronaldson** [comment]
This looks really good! I think I only see one issue with the non status example. The green button with white text doesn't look accessible.

**Comment by nicolethoen** [comment]
I can definitely clean up those style things once this merges 👍🏻 
I agree with @andrew-ronaldson! I think the layout and images look fabulous.

**Comment by edonehoo** [comment]
@nicolethoen @andrew-ronaldson do we think this can be merged? 👀

**Pull request merged**
