### PR TITLE
feat(docs): added Privacy Statement page and link to it in footer

### PR DESCRIPTION
**Pull request by evwilkin**
Partially addresses #1418

### CODE REVIEW

**Comment by redallen** [comment]
There are now 2 different Privacy Statements. One we just created, and one that links to redhat.com's.
image

**Comment by evwilkin** [comment]
@rachael-phillips @abigaeljamie do we still want this separate PF privacy statement linked to in the footer, just above the global footer that links to the Red Hat privacy statement (see screenshot above)?

The GDPR banner is live on the site & links to the Red Hat privacy statement, so currently there are no links pointing to [this PF privacy statement](https://patternfly-org-pr-1584-org.surge.sh/v4/privacy-statement)

**Comment by abigaeljamie** [comment]
I'm not sure if we should be linking to it... @rachael-phillips , do you know?

**Comment by evwilkin** [comment]
Closed in #1703 as we mirrored redhat.com banner

**Pull request closed without merging**
