### PR TITLE
Adding js info updates and repos page to patternfly-org

### PR DESCRIPTION
**Pull request by amarie401**
A part of this jira story: https://patternfly.atlassian.net/browse/PTNFLY-2843

## Changes
* Modified the code section of overview
* Deleted the download page
* Add Repositories page with content updates

## Rawgit Link
[Overview](https://rawgit.com/amarie401/patternfly-org/js-info-site-dist/_site/get-started/)
[Repositories](https://rawgit.com/amarie401/patternfly-org/js-info-site-dist/_site/get-started/repositories/)

### CODE REVIEW

**Comment by amarie401** [comment]
@LHinson I am trying to tag and add Stacy as reviewer but cannot find her username.

**Comment by stacymcauliffe** [comment]
Our Repos - _I think using "Repos" is fine here. We could also use "Resources" and make use this section to house repos and links out to the design kits if we need to include more here in the future._

PatternFly is built on top of Bootstrap 3 and is licensed Apache 2.0. There are also a number of available PatternFly JS framework implementations.

PatternFly
PatternFly Core contains the HTML, CSS, and JQuery _for the PatternFly pattern library_ (@LHinson is that accurate?). All JS framework implementations of PatternFly have a dependency on Core.
Visit the PatternFly GitHub Repo

Angular PatternFly
Angular PatternFly contains the code for a set of Angular 1 components.
Visit the Angular PatternFly GitHub Repo

PatternFly Ng
PatternFly Ng contains the code for a set of Angular 4+ components.
Visit the PatternFly Ng GitHub Repo

PatternFly React
PatternFly React contains the code for a set of React components.
Visit the PatternFly React GitHub Repo

**Comment by LHinson** [comment]
OK, let's stick to "Repos". "Resources" is a little more complex since we have resources under "Styles" as well. For that reason, let's stick to Repos for now and we can revisit consolidating, if necessary, at a later date. 

@stacymcauliffe across all the repos, it is "for the PatternFly pattern library". Not sure if there is a way to make that statement once, up front to apply to all?

**Comment by amarie401** [comment]
So are we adding "for the PatternFly pattern library" or is this good to go? @stacymcauliffe @LHinson ?

**Comment by stacymcauliffe** [comment]
@amarie401 -- Sorry! Yes, let's add "for the PatternFly pattern library"  to the PF core description. Thanks!

**Comment by amarie401** [comment]
The updated text has been changed. If all else is good, then this should be good to merge @stacymcauliffe @LHinson

**Comment by jeff-phillips-18** [comment]
Should it be 'Repos' or 'Repositories' ? I'd lean towards the later.

**Comment by amarie401** [comment]
I would agree @jeff-phillips-18 

Also by changing the directory name from `our-repos` to just `repos` I noticed there is a conflict because `repos` is also the name of the folder that gets generated which has the clones/references to the other framework repos and it gets ignored in the `.gitignore` file.  Just note that the current path  will have to be `patternfly-org/get-started/our-repos/` but the title will be Repos.

To avoid the conflict we can simply change the name to Repositories or keep as is.

**Comment by LHinson** [comment]
"Repositories" works for me and glad it resolves a conflict. Thanks @amarie401 @jeff-phillips-18

**Comment by amarie401** [comment]
Updates have been made. Should be good for a merge now @LHinson @jeff-phillips-18 @stacymcauliffe

**Pull request merged**
