### PR TITLE
replaced toolbar image

### PR DESCRIPTION
**Pull request by kelseamann**
replaced image to reflect new guidelines on buttons in the toolbar. not ready to close at this time, still have to update tables

### CODE REVIEW

**Comment by kelseamann** [comment]
closes #3473

**Comment by kelseamann** [comment]
Still working on this please don't merge yet- finding more as I work on other PF issues

**Comment by kelseamann** [comment]
@mmenestr I've replaced all the ones I can find for now- free to merge

**Comment by mmenestr** [comment]
@kelseamann Messaged you on slacks with all remaining instances where images need to be updated!

**Pull request closed without merging**
