### PR TITLE
Image Update

### PR DESCRIPTION
**Pull request by Rohoover**
Image Update to PatternFly Masthead

### CODE REVIEW

**Comment by dlabrecq** [comment]
LGTM

**Comment by dlabrecq** [comment]
The changes look good, but there are conflicts that need to be resolved. This happens when someone makes a change to the same file you're working on. Did you sync (pull the latest) before making changes?

**Comment by Rohoover** [comment]
Yes I believe I did, but I wouldn't put money on it.

**Comment by dlabrecq** [comment]
If it's been a while since your last sync, changes may have been merged since then. You'll want to sync often.

That said, it appears that the conflict is with recent changes to the index.md page for notification drawer. I've merged your changes with my repository, so we can close this PR -- it will be easier this time. 

Be on the look out for the "This branch has conflicts that must be resolved" message on your PR page. GitHub Desktop may show the message as well? If you have a conflict, please follow the "command line instructions" provided in your PR page -- see below. Alternatively, you can always start over with a fresh sync.

**Comment by Rohoover** [comment]
Thanks Dan! If it happens again, I'll check for it and get a hold of you if I can't figure it out.

**Pull request closed without merging**
