### PR TITLE
Bug Fix

### PR DESCRIPTION
**Pull request by kybaker**
• New About screen design image - /patternfly-org/issues/192
• New images for Trend Card design - /patternfly-org/issues/142

### CODE REVIEW

**Comment by dlabrecq** [comment]
Need to resolve the conflicts for a successful merge. You may just need to update your workspace?

**Comment by dtaylor113** [comment]
LGTM, although not sure why patternfly-site.css.map was updated

**Comment by dlabrecq** [comment]
That file is simply missing form the git ignore file. Was going to include it, but we're planning to generate all files, again, for hot deploy.

**Comment by kybaker** [comment]
Resolved, it was the .map file

**Comment by dtaylor113** [comment]
I just merged another PR, you'll need to rebase.
Thanks,
- Dave

**Pull request merged**
