### PR TITLE
chore: Add information about evaluating beta component stability

### PR DESCRIPTION
**Pull request by nicolethoen**
After fielding questions about beta components in slack, I am proposing we add some of my answers to the website.

### CODE REVIEW

**Review by mcarrano — DISMISSED** [review]
I think this looks fine. Hopefully will help understand what beta components are and how to use them.

**Review by evwilkin — APPROVED** [review]
LGTM - thanks for adding this 👍

**Comment by evwilkin** [comment]
@nicolethoen sorry for the delay, looks like there are conflicts now - if you can update I'll confirm & merge

**Review by evwilkin — APPROVED** [review]
LGTM

**Pull request merged**
