### PR TITLE
updated the color pattern.

### PR DESCRIPTION
**Pull request by zhutaoredhat**
"For Adobe Photoshop" = PatternFly_Swatches_02-27-2017.aco
    "For Adobe Illustrator/InDesign" = "PatternFly_Swatches_02-27-2017.ase
    Last updated date should be changed to "27 Feb 2017"
@LHinson

### CODE REVIEW

**Comment by LHinson** [comment]
This addresses #371 

+1 from me. Mind also checking @bleathem or @andresgalante ?

**Comment by bleathem** [comment]
Since you changed the filename, you'll need to update the download links as well.

```
source/styles/color-palette/index.md
478:              <li><a href="/assets/file/PatternFly_Swatches_08-31-2016.ase">For Adobe Illustrator/Indesign</a></li>
```

**Comment by zhutaoredhat** [comment]
@bleathem hi Brian, Updated just now. Thank you~

**Comment by bleathem** [comment]
Thanks for the update @zhutaoredhat

**Pull request merged**
