### PR TITLE
Adding updated login code to pf-org

### PR DESCRIPTION
**Pull request by amarie401**
Updating and adding the new login code to pf org.

Note: The footer css for the site was interfering with the footer in the login code so I added a class to the footer template to make it more specific to the site.

login

Additional Note: the sidebar looks like that due to the screenshot chrome extension. 

To test locally:
```
git clone git@github.com:amarie401/patternfly-org.git
cd patternfly-org
git checkout update-login-code
```
follow these instructions: https://github.com/patternfly/patternfly-org#development-setup---manually

### CODE REVIEW

**Comment by LHinson** [comment]
Thanks @amarie401 I'm afraid to give approval on this one since I'm not so sure how it works. Will defer to @matthewcarleton @cliffpyles

**Comment by matthewcarleton** [comment]
Hey @amarie401 I'm looking at this and seeing a broken image for the pf logo on the code page. I'm also getting 404's on the "Single Sign-on" and "Identity First Login" links on the overview page. Can you confirm these are working?

**Comment by amarie401** [comment]
@matthewcarleton the image won't show up locally unless you change the path. You can change it to `/patternfly-org/assets/img/Logo_Horizontal_Reversed.svg` if you want to view locally. The way the images are set up it seems to be brought in dynamically. The `login-basic.html` file on pf-core points it's img to `src="{{site.assets-base}}/{{site.brand-horizontal}}"` I made sure to include the `brand-horizontal` variable in the config file and have it point to `assets/img/Logo_Horizontal_Reversed.svg` so that the site could use it.  Hope that explains it.

As far as the Single Sign-on and Identity First Login it seems that this is also not working on patternfly.org. I'm assuming in the design repo in the `site.md` overview - it is not pointing to any path (I see a # in the href). Could you open up an issue on pf-design for this?

**Comment by matthewcarleton** [comment]
@amarie401 thanks! I was wondering if that was the case, I've seen that before. 

I will file that issue. It looks like identity first is the one not working on patternfly.org.

**Pull request merged**
