### PR TITLE
Add component descriptions/design-snippets [WIP]

### LINKED ISSUE #1489: Add Component descriptions and corresponding design guideline links
This work should be completed after issue #1486 

**Core** (Components that map 1:1 with core are accounted for below, and any changes should be applied to the Core examples)

- About modal box
- Alert group
- Backdrop
- Check
- Chip
- Content
- Form control
- Modal box
- Tab content
- Title
- Toolbar
- Alert
- About modal
- Basic forms
- Card view
- Data list
- Modal
- Table
- Wizard
- Divider
- Overflow menu

**React**
*Add new description + link to design guidelines**
- Notification badge
- Topology view

**Add new link to design guidelines**
- Accordion
- Application launcher
- Background image
- Badge
- Brand
- Card
- Clipboard copy
- Dropdown
- Empty state
- Label
- List
- Options menu
- Popover
- Skip to content
- Tabs
- Text
- Title
- Tooltip
- Wizard
- Page layout
- Pagination table
- Toolbar
- Data toolbar
- Drawer 
- Spinner

- All layouts

### PR DESCRIPTION
**Pull request by mcarrano**
Adding missing design snippets and links per #1489 

Closes #1489

### CODE REVIEW

**Comment by mcarrano** [comment]
@evwilkin This PR includes the files that I want to add. You will see there are naming conflicts between the following files:

'data-toolbar' and 'data-toolbar-demo'
'drawer' and 'drawer-demo'
'page' and 'page-layout'

Let me know if there's anything to do from my end.

**Comment by redallen** [comment]
@mcarrano The demos weren't really meant to have a design snippet at the top. Could you settle for editing the MD files in Core and/or React?

https://github.com/patternfly/patternfly-next/tree/master/src/patternfly/demos
https://github.com/patternfly/patternfly-next/tree/master/src/patternfly/demos

For Page/PageLayout, what exactly is the issue?

**Comment by mcarrano** [comment]
We could go that route @redallen . What do you think @rachael-phillips ? I think that the demos do need some explanation because it's not always very clear what they demonstrate.

So for Page and Page Layout, in core there is both a Page component and demo. You will see that both currently pick up the same text. This is not a huge problem but wanted to point it out.

**Comment by redallen** [comment]
Ah, I can add something to this PR that disables showing design snippets on demos. The reason it's currently doing it is because the url matches.

**Comment by rachael-phillips** [comment]
HI @mcarrano and @redallen I think we should keep the description text in some form. It is confusing what they represent without it.

**Comment by mcarrano** [comment]
@redallen I made a few updates to fix some problems I found with the content, but this should be good to merge now. We decided to leave the descriptions off of the Demos for now, but I will open a new issue to revisit this in the future.

**Pull request merged**
