### PR TITLE
Modified overview to show pattern thumbnails per updated wireframes.

### PR DESCRIPTION
**Pull request by dlabrecq**

### CODE REVIEW

**Comment by dlabrecq** [comment]
I case anyone is wondering, I'm experimenting with GitHub desktop, so you'll see two commits here. Want to see how Leslie and others would squash commits using GitHub Desktop.

**Comment by dtaylor113** [comment]
Hi Dan, something I learned from working with the MiQ dev team is that a picture is worth a thousand words -could you add a screenshot of the "overview pattern thumbnails"?  Just so we know what has changed in this PR.  -thanks!

**Comment by dtaylor113** [comment]
LGTM

**Comment by dlabrecq** [comment]
The overview page is rather long, but here are a couple screen shots.

screen shot 2016-05-04 at 2 18 04 pm
screen shot 2016-05-04 at 2 19 37 pm

**Comment by LHinson** [comment]
nice @dlabrecq! Want to pass this by @kybaker as well for visual comments

**Pull request merged**
