### PR TITLE
Show/hide functionality does not work on Vertical Nav

### PR DESCRIPTION
**Pull request by dabeng**
Fix the bug: [Show/hide functionality does not work on Vertical Nav example code when accessed from web site.](https://github.com/patternfly/patternfly/issues/607)

### CODE REVIEW

**Comment by michpetrov** [comment]
@dabeng  I was about to submit a PR and then I noticed yours. Anyway, there are 12 links for jquery.matchHeight-min.js, you should change all of them.

**Comment by dabeng** [comment]
Hi @michpetrov, thank you for your reminding 😊 . While I think minimal modification for a particular issue is a good practice and then we can get the limited testing scope 😊

**Comment by michpetrov** [comment]
I don't think that's a good practice, especially in this case where the only problem is the wrong/outdated path, the widget itself has been already tested.

**Comment by bleathem** [comment]
Why are we making this change?  It seems the `jquery-match-height` project ships the minified js file in both the root and dist folders.

```
$ tree _build/components/jquery-match-height/
_build/components/jquery-match-height/
├── bower.json
├── CHANGELOG.md
├── dist
│   ├── jquery.matchHeight.js
│   └── jquery.matchHeight-min.js
├── gulpfile.js
├── jquery.matchHeight.js
├── jquery.matchHeight-min.js
...
```

**Comment by dabeng** [comment]
Hi @bleathem , I can't see the minified version of jquery.matchHeight.
screen shot 2017-03-09 at 2 04 44 pm

**Comment by michpetrov** [comment]
@bleathem @dabeng it was removed a while ago - liabru/jquery-match-height@f530833 as far as I can tell npm doesn't clean up extraneous files.

**Comment by bleathem** [comment]
Thanks for pointing that our @michpetrov.  I removed the node_modules folder, and ran `npm install`, and indeed the minified file is not present.

@dabeng can you please expand the scope of this PR to replace all incorrect file references?  We might as well fix them in one swoop.

**Comment by dabeng** [comment]
OK. no question.

**Comment by LHinson** [comment]
@dabeng has Brian's comment about replacing all incorrect file references been addressed?

**Comment by dabeng** [comment]
@LHinson , current PR has fixed all incorrect references. Don't worry. @michpetrov , would you review again?

**Comment by LHinson** [comment]
OK thanks @dabeng @michpetrov! I'll merge it. 

Do we have issues filed for the bad links? Sorry I'm so lost on this one @michpetrov If you point them out to me, I'm happy to file the issues too. Thanks!

**Comment by michpetrov** [comment]
@LHinson you have now - patternfly/patternfly-design#237

**Comment by LHinson** [comment]
Appreciated @michpetrov!

**Pull request merged**
