### PR TITLE
PTNFLY-1423 Toolbar Page.

### PR DESCRIPTION
**Pull request by cardosogabriel**

### CODE REVIEW

**Comment by cardosogabriel** [comment]
This depends on the code created in https://github.com/patternfly/patternfly/pull/417.
@dlabrecq , there are two commits here. Think it is not so good, but let me know if it is still ok.

**Comment by dlabrecq** [comment]
It would be best to create separate PRs for each commit. Right now the Travis build won't complete because of the patternfly/patternfly#417 dependency. If they were separate, we could at least merge one of the commits now.

**Comment by cardosogabriel** [comment]
Ok, updated the pr splitting the commits, therefore I created another PR also. Thanks for the feedback.

**Comment by cardosogabriel** [comment]
For this one we need to wait for the patternfly next bump?

**Comment by dlabrecq** [comment]
Yes, we have to wait for the next release of patternfly because of the dependency. As you can see above, the Travis build fails to compile without the right version of patternfly. When the next release is available, this should turn green. We might need to regenerate the Travis build to test, again?

**Comment by cardosogabriel** [comment]
No problem. I'll rebase whenever we get the next release.

**Comment by dlabrecq** [comment]
@cardosogabriel Patternfly has been released. If you want to resolve the conflicts and rebuild, I believe we can merge now?

**Comment by LHinson** [comment]
How can i tell where the toolbar is getting added to on the site?  @cardosogabriel

**Comment by cardosogabriel** [comment]
@dlabrecq , rebuild and conflicts are resolved.
@LHinson, sorry, I don't understand your question. What do you mean?

**Comment by dlabrecq** [comment]
Travis looks like it built successfully now. :)

Before I click the merge button; @LHinson, do you have any issues that need to be addressed?

**Comment by LHinson** [comment]
@dlabrecq @cardosogabriel just curious where it was posted on the site. Under which navigation item does it live?

**Comment by cardosogabriel** [comment]
@LHinson , as specified in this Jira, it goes under Forms and Controls.
https://patternfly.atlassian.net/browse/PTNFLY-1423

**Comment by LHinson** [comment]
Thanks @cardosogabriel :) Let's get this merged!

**Pull request merged**
