### PR TITLE
Chore/2056 animate search

### LINKED ISSUE #2056: Animate search input
Animate search or add jump as seen in [Carbon](https://www.carbondesignsystem.com/)

### PR DESCRIPTION
**Pull request by evwilkin**
Closes #2056 

This PR hides the global search input by default, adds functionality to expand it when clicking on the search icon, and when open adds a close icon that hides the search input.

### CODE REVIEW

**Comment by redallen** [comment]
I find this design confusing. Am I searching versions? If this is meant to be a search box, where is the search input? When I click the button the experience is not what I expect. There's tons of space available to have the search box always visible, why not just always show it @rachael-phillips ?
image

**Comment by rachael-phillips** [comment]
I think it's looking good. @redallen you have a good point - would it be possible to make this look more like a focus and a search box? The grey hear enhances that separation. 

Screen Shot 2020-09-10 at 2 59 31 PM
Screen Shot 2020-09-10 at 2 59 38 PM

**Comment by evwilkin** [comment]
@rachael-phillips happy to update the styling, can you elaborate a bit on the design changes needed - do we want to add a grey background color to the search button and text input to mirror your example above?

**Comment by rachael-phillips** [comment]
@redallen @evwilkin after talking with Michael and visual design there are no other updates that need to be added here. The only bug we are seeing is with Firefox. Search background disappears. 
image (7)

**Review by rachael-phillips — APPROVED** [review]

**Comment by evwilkin** [comment]
Firefox styling issue resolved in #2120

**Comment by evwilkin** [comment]
@rachael-phillips do you mind re-reviewing? Lost your review when working on the Firefox bug but @redallen put up [another PR](https://github.com/patternfly/patternfly-org/pull/2120) to resolve that issue. Thanks!

**Review by rachael-phillips — APPROVED** [review]
LGTM!

**Pull request merged**
