### PR TITLE
Applying max-width for content area of Patternfly-Library components.

### PR DESCRIPTION
**Pull request by cardosogabriel**
- Added max-width to all tabs inside the pattern-library components
- Created a new layout for widgets page, to be able to apply the max-width
- Limited the Code box to the height of the viewport, to avoid double scroll when seeing the code.

### CODE REVIEW

**Comment by dlabrecq** [comment]
Limiting the viewport height seems reasonable. (I vaguely recall some discussion about doing that.) However, can you please explain why the other changes are necessary? Is there a JIRA story I can look at? Thanks.

**Comment by cardosogabriel** [comment]
Sure, the JIRA is the PTNFLY-1536: https://patternfly.atlassian.net/browse/PTNFLY-1536
Plus Andrés and Leslie gave me further details in a Slack conversation. Thanks

**Comment by andresgalante** [comment]
@LHinson @dlabrecq Are we merging this?

**Comment by LHinson** [comment]
@dlabrecq we want to apply the max width for two reasons: 1) to give the user a margin to scroll so they don't get stuck in the embedded code window 2) to improve legibility. 

We wanted to provide a max height for code because right now there is pages and pages of scrolling.

**Comment by dlabrecq** [comment]
The JIRA story states "text still goes above the 45 - 75 characters per line recommended". I'm fine with it, but just wanted to make sure @LHinson reviewed it.

Still need to fix the merge conflicts, tho.

**Comment by LHinson** [comment]
@dlabrecq @cardosogabriel @andresgalante I'm not sure the best way for me to check this :/

**Comment by dlabrecq** [comment]
The best way would be to walk through it with @cardosogabriel. Otherwise, you would need to pull the latest and build locally. I can help you with that if you want to go that route?

**Comment by andresgalante** [comment]
@dlabrecq @LHinson I'll get @cardosogabriel in a call whenever he is avaliable and screen share

**Comment by LHinson** [comment]
that sounds like a good plan @andresgalante. just let me know. thanks guys.

**Comment by cardosogabriel** [comment]
Met with @andresgalante and we agreed to limit more the height of the code snipet to the equivalent to 20 lines of code. I did in a way that the limit is in the middle of the text so this is the affordance to know that more code can be found scrolling.

code snippet

**Comment by cardosogabriel** [comment]
@dlabrecq can u merge please?

**Pull request merged**
